### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by carloscarcamo** [alexbananabob/dashboard#15]
Hello, I was trying to build the project and I got this:

```
$ gulp build
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/home/user/dashboard/node_modules/gulp-sass/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/home/userdashboard/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:74:13)
    at foundBinariesList (/home/user/dashboard/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/user/dashboard/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/user/dashboard/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/home/user/dashboard/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

System info:
- Ubuntu 14.04
- Node v4.4.5
- npm 2.15.5

any thoughts? thanks in advance.

**Comment by randrianov** [comment]
Operating system? Windows?

**Comment by carloscarcamo** [comment]
Ubuntu Linux 14.04

**Comment by the4ndy** [comment]
Can you make releases or downloadable Zips of the flat HTML, CSS, and JS files? can it be run on webserver without Node, Gulp, etc?

**Comment by randrianov** [comment]
@the4ndy look our release here https://github.com/CreativeIT/material-dashboard-lite/releases/tag/v1.0.0-b inside you will find 'dist' folder, exactly what you asked for.

**Comment by franckevva** [comment]
Hey,  @carloscarcamo 
I can't reproduce your problem. 
My system info: Ubuntu 15.10, Node v4.4.5, npm 2.15.5
Try to remove all node_modules and  install it one more. 

You have a problem with gulp-sass. Look on this point.

**Comment by claudioc** [comment]
I have the same problem, with the same configuration (Ubu 14.04)

Apparently the `vendor` directory is missing, not created, and readdir fails.

**Comment by ghost** [comment]
same problem (arch)

**Comment by redaawad622** [comment]
from package.json change gulp-sass and node-sass version to :

"gulp-sass": "4.0.2",   
"node-sass": "^4.12.0"

then run :
npm install

gulp build

**Comment by dieseld23** [comment]
make sure you're also using node v12 or less
