### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by yajushiSri** [alexbananabob/dashboard#22]
**# gulp serve**

module.js:328
    throw err;
    ^

Error: Cannot find module 'gulp-jscs'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/yajushi/Desktop/material-dashboard-lite/gulpfile.js:2:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

**Comment by aailyin** [comment]
@yajushiSri Did you run `npm install`? I cannot reproduce it.
